module.exports = Object.freeze({
    ACTION_KILL_ME: 'killMe',
    ACTION_SNAPSHOT_PM2: 'snapshotPM2',
    ACTION_PROFILE_START: 'profileStart',
    ACTION_PROFILE_STOP: 'profileStop',
    ACTION_PREPARE: 'prepare',
    ACTION_GET_MONITOR_DATA: 'getMonitorData',
    ACTION_GET_SYSTEM_DATA: 'getSystemData',
    ACTION_START_PROCESS_ID: 'startProcessId',
    ACTION_STOP_PROCESS_ID: 'stopProcessId',
    ACTION_RESTART_PROCESS_ID: 'restartProcessId',
    ACTION_DELETE_PROCESS_ID: 'deleteProcessId',
    ACTION_SENDING_LINE_TO_STDIN: 'sendLineToStdin',
    ACTION_SOFT_RELOAD_PROCESS_ID: 'softReloadProcessId',
    ACTION_RELOAD_PROCESS_ID: 'reloadProcessId',
    ACTION_DUPLICATE_PROCESS_ID: 'duplicateProcessId',
    ACTION_RESET_META_PROCESS_ID: 'resetMetaProcessId',
    ACTION_STOP_WATCH: 'stopWatch',
    ACTION_START_WATCH: 'startWatch',
    ACTION_TOGGLE_WATCH: 'toggleWatch',
    ACTION_NOTIFY_BY_PROCESS_ID: 'notifyByProcessId',
    ACTION_NOTIFY_KILL_PM2: 'notifyKillPM2',
    ACTION_FORCE_GC: 'forceGc',
    ACTION_MONITOR: 'monitor',
    ACTION_UNMONITOR: 'unmonitor',
    ACTION_MSG_PROCESS: 'msgProcess',
    ACTION_SEND_DATA_TO_PROCESS_ID: 'sendDataToProcessId',
    ACTION_SEND_SIGNAL_TO_PROCESS_ID: 'sendSignalToProcessId',
    ACTION_SEND_SIGNAL_TO_PROCESS_NAME: 'sendSignalToProcessName',
    ACTION_PING: 'ping',
    ACTION_GET_VERSION: 'getVersion',
    ACTION_GET_REPORT: 'getReport',
    ACTION_RELOAD_LOGS: 'reloadLogs',

});